# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkE7wiO9lbYGnh9v9UcJdqxMP45j5ikv
"""

import pandas as pd
import numpy as np

# Creating a sample dataset
data = {
    'Transaction ID': range(101, 111),
    'Date': ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-07', '2024-02-10',
             '2024-02-12', '2024-03-15', '2024-03-16', '2024-03-17', '2024-03-18'],
    'User ID': [1, 2, 1, 3, 4, 2, 5, 1, 4, 3],
    'Book Title': ['Python Basics', 'Data Science 101', 'Python Basics', 'Machine Learning',
                   'Deep Learning', 'Data Science 101', 'Python Basics', 'NLP Guide', 'Deep Learning', 'Python Basics'],
    'Genre': ['Tech', 'Tech', 'Tech', 'AI', 'AI', 'Tech', 'Tech', 'AI', 'AI', 'Tech'],
    'Borrowing Duration (Days)': [5, 7, 3, 10, 14, 2, 8, 5, 12, 4]
}

df = pd.DataFrame(data)
df.to_csv('library_transactions.csv', index=False)
print("Sample dataset 'library_transactions.csv' created successfully.")

import pandas as pd
import numpy as np

def load_data(file_path):
    try:
        df = pd.read_csv(file_path)
        if df.empty:
            print("File is empty")
            return None

        df['Date'] = pd.to_datetime(df['Date'])
        print("Data loaded successfully\n")
        return df
    except Exception as e:
        print("Error loading file:", e)
        return None

def calculation(df):

    most_borrowed = df['Book Title'].mode()[0]

    avg_days = np.mean(df['Borrowing Duration (Days)'])

    busiest_day = df['Date'].dt.day_name().mode()[0]

    return most_borrowed, avg_days, busiest_day

def show_info(df):

    high_book, avg, day = calculation(df)

    print("information")
    print(f"Most Borrowed Book: {high_book}")
    print(f"Average Borrow Time: {round(avg, 2)} days")
    print(f"Busiest Day: {day}")
    print("\n")

file_name = "library_transactions.csv"


data = load_data(file_name)

if data is not None:
    show_info(data)